PREFIX ns1: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ns2: <http://sws.ifi.uio.no/vocab/npd-v2#>
PREFIX ns3: <http://sws.ifi.uio.no/vocab/npd-v2-ptl#>
SELECT ?c1 ?c2 ?a3 WHERE {
?c1 ns1:type ns2:Wellbore.
?c1 ns2:idNPD ?a3.
?c2 ns1:type ns2:Field.

FILTER(?a3 >= 2000 && ?a3 <= 2022).
}
